# 00-healthy-app.yaml
# A healthy, working application for baseline comparison
# This pod should run successfully without any issues

apiVersion: v1
kind: Pod
metadata:
  name: healthy-app
  namespace: troubleshooting-demo
  labels:
    app: healthy-app
    scenario: healthy
    demo: troubleshooting
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
          name: http
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      # Health checks to demonstrate healthy pod
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
  restartPolicy: Always

